spring:
  profiles:
    active:
    - dev
---
spring:
  profiles:
  application:
    name:microservicecloud-config-xinyan-dev
---
spring:
  profiles:
  application:
  name:microservicecloud-config-xinyan-test